name = "cb-server"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "WEBFLOW_AUTHENTICATION"
id = "aa64050ef7804e7783fe9680daae80c5"
[[kv_namespaces]]
binding = "CMP_MANUAL"
id = "00daba26dc5a43a2a40f5e42039907fa"



[secrets]
SERVER_ENCRYPTION_KEY=""
CLIENT_SECRET =""
CLIENT_ID =""